In [ ]:
import numpy as np

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

print(a)

[1 2 3 4]

In [ ]:
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a ** 2)

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
[ 1  4  9 16]

In [ ]:
print(np.sum(a))
print(np.mean(a))
print(np.min(a))
print(np.max(a))

print(np.sqrt(a))
print(np.std(a))

10
2.5
1
4
[1.         1.41421356 1.73205081 2.        ]
1.118033988749895

In [ ]:
print(a[0])
print(a[-1])
print(a[1:4])

1
4
[2 3 4]

In [ ]:
import pandas as pd

In [ ]:
data = {
    "Name": ["Asha", "Ravi", "John"],
    "Age": [20, 21, 19],
    "Marks": [85, 90, 78]
}

df = pd.DataFrame(data)

print(df)

   Name  Age  Marks
0  Asha   20     85
1  Ravi   21     90
2  John   19     78

In [ ]:
df.head()

   Name  Age  Marks
0  Asha   20     85
1  Ravi   21     90
2  John   19     78

In [ ]:
df.head(2)

   Name  Age  Marks
0  Asha   20     85
1  Ravi   21     90

In [ ]:
df.tail()

   Name  Age  Marks
0  Asha   20     85
1  Ravi   21     90
2  John   19     78

In [ ]:
print(df["Name"])

0    Asha
1    Ravi
2    John
Name: Name, dtype: object

In [ ]:
print(df.shape)

(3, 3)

In [ ]:
print(df.loc[0])

Name     Asha
Age        20
Marks      85
Name: 0, dtype: object

In [ ]:
print(df.iloc[0])

Name     Asha
Age        20
Marks      85
Name: 0, dtype: object