In [ ]:
import pandas as pd
data={
    "Student_ID":[1,2,3,4,5,6,7],
    "Student":["Asha","Ravi","Kiran","John","Mohan","Ravi","Meena"],
    "Department":["CSE","ECE","CSE","CSE","ECE","MECH","CIVIL"],
    "Attendence":[90,70,50,20,99,80,77],
    "Internal_Marks":[35,66,77,88,99,88,34],
    "Final Marks":[55,66,77,33,44,59,None]
    }
df=pd.DataFrame(data)
df.to_csv("students.csv",index=False)
print("students.csv created successfully!")
df=pd.read_csv("students.csv")
print("Original Dataset:")
print(df)

students.csv created successfully!
Original Dataset:
   Student_ID Student Department  Attendence  Internal_Marks  Final Marks
0           1    Asha        CSE          90              35         55.0
1           2    Ravi        ECE          70              66         66.0
2           3   Kiran        CSE          50              77         77.0
3           4    John        CSE          20              88         33.0
4           5   Mohan        ECE          99              99         44.0
5           6    Ravi       MECH          80              88         59.0
6           7   Meena      CIVIL          77              34          NaN

In [ ]:
print(df.head())

   Student_ID Student Department  Attendence  Internal_Marks  Final Marks
0           1    Asha        CSE          90              35         55.0
1           2    Ravi        ECE          70              66         66.0
2           3   Kiran        CSE          50              77         77.0
3           4    John        CSE          20              88         33.0
4           5   Mohan        ECE          99              99         44.0

In [ ]:
print(df.head(3))

   Student_ID Student Department  Attendence  Internal_Marks  Final Marks
0           1    Asha        CSE          90              35         55.0
1           2    Ravi        ECE          70              66         66.0
2           3   Kiran        CSE          50              77         77.0

In [ ]:
print(df.head(10))

   Student_ID Student Department  Attendence  Internal_Marks  Final Marks
0           1    Asha        CSE          90              35         55.0
1           2    Ravi        ECE          70              66         66.0
2           3   Kiran        CSE          50              77         77.0
3           4    John        CSE          20              88         33.0
4           5   Mohan        ECE          99              99         44.0
5           6    Ravi       MECH          80              88         59.0
6           7   Meena      CIVIL          77              34          NaN

In [ ]:
print(df.head(0))

Empty DataFrame
Columns: [Student_ID, Student, Department, Attendence, Internal_Marks, Final Marks]
Index: []

In [ ]:
print(df.tail())

   Student_ID Student Department  Attendence  Internal_Marks  Final Marks
2           3   Kiran        CSE          50              77         77.0
3           4    John        CSE          20              88         33.0
4           5   Mohan        ECE          99              99         44.0
5           6    Ravi       MECH          80              88         59.0
6           7   Meena      CIVIL          77              34          NaN

In [ ]:
print(df.tail(3))

   Student_ID Student Department  Attendence  Internal_Marks  Final Marks
4           5   Mohan        ECE          99              99         44.0
5           6    Ravi       MECH          80              88         59.0
6           7   Meena      CIVIL          77              34          NaN

In [ ]:
print(df.shape)

(7, 6)

In [ ]:
df.dtypes

Student_ID          int64
Student            object
Department         object
Attendence          int64
Internal_Marks      int64
Final Marks       float64
dtype: object

In [ ]:
print("Descriptive Statistics")
df.describe()

Descriptive Statistics

       Student_ID  Attendence  Internal_Marks  Final Marks
count    7.000000    7.000000        7.000000     6.000000
mean     4.000000   69.428571       69.571429    55.666667
std      2.160247   26.732360       26.056715    15.641824
min      1.000000   20.000000       34.000000    33.000000
25%      2.500000   60.000000       50.500000    46.750000
50%      4.000000   77.000000       77.000000    57.000000
75%      5.500000   85.000000       88.000000    64.250000
max      7.000000   99.000000       99.000000    77.000000

In [ ]:
print("MISSING VALUES")
print(df.isnull().sum())

MISSING VALUES
Student_ID        0
Student           0
Department        0
Attendence        0
Internal_Marks    0
Final Marks       1
dtype: int64

In [ ]:
print("DUPLICATE")
print(df.duplicated().sum())
df=df.drop_duplicates()

DUPLICATE
0

In [ ]:
from google.colab import files
uploaded=files.upload()

Saving student_data.csv to student_data.csv

In [ ]:
df=pd.read_csv(r"student_data.csv")
print(df.describe())
print("MISSING VALUES",df.isnull().sum())
print("DUPLICATE",df.duplicated().sum())

              age        Medu        Fedu  traveltime   studytime    failures  \
count  395.000000  395.000000  395.000000  395.000000  395.000000  395.000000
mean    16.696203    2.749367    2.521519    1.448101    2.035443    0.334177
std      1.276043    1.094735    1.088201    0.697505    0.839240    0.743651
min     15.000000    0.000000    0.000000    1.000000    1.000000    0.000000
25%     16.000000    2.000000    2.000000    1.000000    1.000000    0.000000
50%     17.000000    3.000000    2.000000    1.000000    2.000000    0.000000
75%     18.000000    4.000000    3.000000    2.000000    2.000000    0.000000
max     22.000000    4.000000    4.000000    4.000000    4.000000    3.000000

           famrel    freetime       goout        Dalc        Walc      health  \
count  395.000000  395.000000  395.000000  395.000000  395.000000  395.000000
mean     3.944304    3.235443    3.108861    1.481013    2.291139    3.554430
std      0.896659    0.998862    1.113278    0.890741    1.287897    1.390303
min      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000
25%      4.000000    3.000000    2.000000    1.000000    1.000000    3.000000
50%      4.000000    3.000000    3.000000    1.000000    2.000000    4.000000
75%      5.000000    4.000000    4.000000    2.000000    3.000000    5.000000
max      5.000000    5.000000    5.000000    5.000000    5.000000    5.000000

         absences          G1          G2          G3
count  395.000000  395.000000  395.000000  395.000000
mean     5.708861   10.908861   10.713924   10.415190
std      8.003096    3.319195    3.761505    4.581443
min      0.000000    3.000000    0.000000    0.000000
25%      0.000000    8.000000    9.000000    8.000000
50%      4.000000   11.000000   11.000000   11.000000
75%      8.000000   13.000000   13.000000   14.000000
max     75.000000   19.000000   19.000000   20.000000
MISSING VALUES school        0
sex           0
age           0
address       0
famsize       0
Pstatus       0
Medu          0
Fedu          0
Mjob          0
Fjob          0
reason        0
guardian      0
traveltime    0
studytime     0
failures      0
schoolsup     0
famsup        0
paid          0
activities    0
nursery       0
higher        0
internet      0
romantic      0
famrel        0
freetime      0
goout         0
Dalc          0
Walc          0
health        0
absences      0
G1            0
G2            0
G3            0
dtype: int64
DUPLICATE 0